-- ============================================================
-- C5 扫货账号独立业务表（PostgreSQL · 追加式 migration）
-- 日期: 2026-04-26
-- 目标:
-- 1. 新增 c5_sniping_account，承载 C5 扫货账号配置，移除对 buff_account.role / platform=C5 的业务依赖
-- 2. 从 buff_account 迁移 platform = 'C5' 的历史账号，并保留原 id，确保 C5 扫货 2.0 任务 / 运行态 / 明细表中的 account_id 可继续匹配
-- 3. 补齐用户维度与状态维度查询索引，并将 identity sequence 调整到当前 max(id)
-- 幂等策略:
-- - 新表使用 create table if not exists，索引使用 create index if not exists
-- - 历史数据按主键 id 做 on conflict upsert，重复执行不会重复插入
-- - identity sequence 使用 pg_get_serial_sequence + setval 按当前 max(id) 重置
-- 回滚思路:
-- - 如需回滚，可新增 migration 将 c5_sniping_account 软弃用或删除，并让业务临时回读 buff_account 中 platform = 'C5' 的数据
-- - 本脚本不修改、不删除 buff_account 及 C5 扫货 2.0 既有任务 / 运行态 / 明细表
-- ============================================================

begin;

create table if not exists public.c5_sniping_account (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    account_name varchar(128) not null,
    status varchar(32) not null default 'NORMAL',
    balance numeric(12, 2) not null default 0,
    pending_balance numeric(12, 2) not null default 0,
    last_check_time timestamp,
    remark varchar(500) not null default '',
    warning_msg varchar(500) not null default '',
    today_scan_count integer not null default 0,
    trade_success_count integer not null default 0,
    trade_total_count integer not null default 0,
    del_flag smallint not null default 0,
    create_time timestamp not null default now(),
    update_time timestamp not null default now(),
    constraint chk_c5_sniping_account_balance check (balance >= 0),
    constraint chk_c5_sniping_account_pending_balance check (pending_balance >= 0),
    constraint chk_c5_sniping_account_today_scan_count check (today_scan_count >= 0),
    constraint chk_c5_sniping_account_trade_success_count check (trade_success_count >= 0),
    constraint chk_c5_sniping_account_trade_total_count check (trade_total_count >= 0),
    constraint chk_c5_sniping_account_del_flag check (del_flag in (0, 1))
);

comment on table public.c5_sniping_account is 'C5扫货账号配置表';
comment on column public.c5_sniping_account.id is '主键ID，迁移自buff_account时保留原账号ID';
comment on column public.c5_sniping_account.user_id is '系统用户ID';
comment on column public.c5_sniping_account.account_name is '账号名称';
comment on column public.c5_sniping_account.status is '账号状态';
comment on column public.c5_sniping_account.balance is '账号可用余额';
comment on column public.c5_sniping_account.pending_balance is '待结算余额';
comment on column public.c5_sniping_account.last_check_time is '最后检测时间';
comment on column public.c5_sniping_account.remark is '备注';
comment on column public.c5_sniping_account.warning_msg is '异常提示信息';
comment on column public.c5_sniping_account.today_scan_count is '今日扫货次数';
comment on column public.c5_sniping_account.trade_success_count is '下单成功总数';
comment on column public.c5_sniping_account.trade_total_count is '下单总数';
comment on column public.c5_sniping_account.del_flag is '逻辑删除标记，0未删除，1已删除';
comment on column public.c5_sniping_account.create_time is '创建时间';
comment on column public.c5_sniping_account.update_time is '更新时间';

create index if not exists idx_c5_sniping_account_user_del
    on public.c5_sniping_account (user_id, del_flag);

create index if not exists idx_c5_sniping_account_user_status_del
    on public.c5_sniping_account (user_id, status, del_flag);

insert into public.c5_sniping_account (
    id,
    user_id,
    account_name,
    status,
    balance,
    pending_balance,
    last_check_time,
    remark,
    warning_msg,
    today_scan_count,
    trade_success_count,
    trade_total_count,
    del_flag,
    create_time,
    update_time
)
select
    ba.id,
    ba.user_id,
    coalesce(ba.account_name, ''),
    coalesce(ba.status, 'NORMAL'),
    coalesce(ba.balance, 0)::numeric(12, 2),
    coalesce(ba.pending_balance, 0)::numeric(12, 2),
    ba.last_check_time,
    coalesce(ba.remark, ''),
    coalesce(ba.warning_msg, ''),
    coalesce(ba.today_scan_count, 0),
    coalesce(ba.trade_success_count, 0),
    coalesce(ba.trade_total_count, 0),
    coalesce(ba.is_deleted, 0),
    coalesce(ba.create_time, now()),
    coalesce(ba.update_time, now())
from public.buff_account ba
where ba.platform = 'C5'
on conflict (id) do update set
    user_id = excluded.user_id,
    account_name = excluded.account_name,
    status = excluded.status,
    balance = excluded.balance,
    pending_balance = excluded.pending_balance,
    last_check_time = excluded.last_check_time,
    remark = excluded.remark,
    warning_msg = excluded.warning_msg,
    today_scan_count = excluded.today_scan_count,
    trade_success_count = excluded.trade_success_count,
    trade_total_count = excluded.trade_total_count,
    del_flag = excluded.del_flag,
    create_time = excluded.create_time,
    update_time = excluded.update_time;

do $$
declare
    seq_name text;
    max_account_id bigint;
begin
    seq_name := pg_get_serial_sequence('public.c5_sniping_account', 'id');
    select max(id) into max_account_id from public.c5_sniping_account;

    if seq_name is not null then
        if max_account_id is null then
            perform setval(seq_name, 1, false);
        else
            perform setval(seq_name, max_account_id, true);
        end if;
    end if;
end $$;

-- 复核 SQL：
-- select count(*) from public.c5_sniping_account;
-- select max(id) from public.c5_sniping_account;

commit;
