/**
 * 前端权限码常量
 */
export const PermissionConstant = {
  TASK_SCAN_LIST: "task:scan:list",
  TASK_SCAN_START: "task:scan:start",
  TASK_SCAN_STOP: "task:scan:stop",
  TASK_SCAN_CREATE: "task:scan:create",
  TASK_RECORD_LIST: "task:record:list",
  TASK_INVENTORY_VIEW: "task:inventory:view",
  TASK_C5_LIST: "task:c5:list",
  C5_INVENTORY_LIST: "c5:inventory:list",
  C5_INVENTORY_REFRESH: "c5:inventory:refresh",
  TASK_C5_SNIPING_V2_LIST: "task:scan:list",
  C5_SNIPING_TASK_CREATE: "c5:sniping-task:create",
  C5_SNIPING_TASK_UPDATE: "c5:sniping-task:update",
  C5_SNIPING_TASK_ENABLE: "c5:sniping-task:enable",
  C5_SNIPING_TASK_DISABLE: "c5:sniping-task:disable",
  C5_SNIPING_TASK_DELETE: "c5:sniping-task:delete",
  C5_SNIPING_TASK_DETAIL: "c5:sniping-task:detail",
  C5_SNIPING_ACCOUNT_CREATE: "c5:sniping-account:create",
  C5_SNIPING_ACCOUNT_UPDATE: "c5:sniping-account:update",
  C5_SNIPING_ACCOUNT_DELETE: "c5:sniping-account:delete",
  C5_SNIPING_ACCOUNT_DETAIL: "c5:sniping-account:detail",

  LOG_LIST: "system:logs:list",
  ACCOUNT_LIST: "system:account:list",
  GOODS_LIST: "system:goods:list",

  ORDER_RECORD_UPDATE: "order:record:update",
  ORDER_RECORD_DELETE: "order:record:delete",
  ORDER_C5_SYNC: "order:c5:sync",

  SETTINGS_SAVE: "system:settings:save",
  INVITE_CODE_MANAGE: "system:invite-code:manage",
  INVITE_CODE_CREATE: "system:invite-code:create",
  INVITE_CODE_BATCH_CREATE: "system:invite-code:batch-create",
  INVITE_CODE_UPDATE: "system:invite-code:update",
  INVITE_CODE_ENABLE: "system:invite-code:enable",
  INVITE_CODE_DISABLE: "system:invite-code:disable",
  INVITE_CODE_COPY: "system:invite-code:copy",

  PERMISSION_RESOURCE_READ: "system:permission:resource:read",
  PERMISSION_ROLE_AUTH_READ: "system:permission:role-auth:read",
  PERMISSION_MANAGE: "system:permission:manage",
  PERMISSION_RESOURCE_SAVE: "system:permission:resource:save",
  PERMISSION_ROLE_CREATE: "system:permission:role:create",
  PERMISSION_ROLE_UPDATE: "system:permission:role:update",
  PERMISSION_ROLE_DELETE: "system:permission:role:delete",
  PERMISSION_ROLE_COPY: "system:permission:role:copy",
  PERMISSION_ROLE_AUTH_SAVE: "system:permission:role-auth:save",
  PERMISSION_USER_ASSIGN: "system:permission:user:assign",
  PERMISSION_ROLE_PREVIEW: "system:permission:role:preview",
  PERMISSION_PUBLISH_VALIDATE: "system:permission:publish:validate",
  PERMISSION_PUBLISH: "system:permission:publish",

  UNBOX_RECORD_CREATE: "unbox:record:create",
  UNBOX_RECORD_UPDATE: "unbox:record:update",
  UNBOX_RECORD_DELETE: "unbox:record:delete",
  UNBOX_RECORD_OCR: "unbox:record:ocr",
  UNBOX_RECORD_QUERY_C5: "unbox:record:query-c5",
  UNBOX_RECORD_DETAIL_ADD: "unbox:record:detail:add",
  UNBOX_RECORD_DETAIL_DELETE: "unbox:record:detail:delete",
  UNBOX_RECORD_APPLY_PRICE: "unbox:record:apply-price",
  UNBOX_RECORD_APPLY_DEFAULTS: "unbox:record:apply-defaults",
} as const;
