version: '1.0'
name: pipeline-20260511
displayName: niro后端构建

triggers:
  trigger: manual
  push:
    branches:
      precise:
        - main
    paths:
      prefix:
        - niro-server/

stages:
  - name: stage-build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor:
      - LYLMagui
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '21'
        mavenVersion: 3.9.11
        commands:
          - mvn -f niro-server/pom.xml clean package -pl niro-web -am -Dmaven.test.skip=true -B
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - niro-server/niro-web/target/*.jar
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'

strategy:
  blocking: true
